config/routes.rb
Zgame::Application.routes.draw do
  devise_for :users

  root :to => 'mains#index'
  resources :games do
    resources :players
  end

  # Join a game via key
  get "/join/:game_key" => "joins#new"

  #update caught status of player
  post "/caught" => "players#caught"

  resources :invites, :only => [:create, :update]
end

app/models/game.rb
class Game < ActiveRecord::Base
  after_create :add_game_key, :include_user_player

  attr_accessible :title, :start, :finish, :entries_close, :game_key

  belongs_to :user
  has_many :players, :dependent => :destroy

  validates_presence_of :title, :start, :finish, :entries_close
  validates_uniqueness_of :title

private

  def add_game_key
    self.game_key = generated_key
    self.save
  end

  def generated_key
    Digest::SHA1.hexdigest(Time.now.to_s + self.id.to_s)
  end

  def self.find_all_by_user_participation(user_email)
    self.joins(:players).where('players.email'=> user_email)
  end

  def include_user_player
    self.players.create(name: self.user.username, email: self.user.email, user_id: self.user.id)
  end
  
end
      

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :from_user_id, :game_id

private

  def self.remove_all_invites_for_game(game_id)
    self.where(game_id: game_id).destroy_all
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name, :email, :role, :user_id
  belongs_to :game

  validates_presence_of :email
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :username

  validates_uniqueness_of :username

  has_many :games
  has_many :invites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_api, :if => :json?

private

  def json?
    request.format.json? && !current_user
  end

  def authenticate_api
    authenticate_or_request_with_http_token do |token, options|
      if User.exists?(:authentication_token => token)
        params[:auth_token] = token
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @games = Game.find_all_by_user_participation(current_user.email)
    @invites = current_user.invites
  end

  def show
    if params[:game_key]
      @game = Game.find_by_game_key(params[:game_key])
    else
      @game = current_user.games.find(params[:id])
    end
    redirect_to root_path unless @game
  end

  def new
    @game = current_user.games.new
  end

  def create
    @game = current_user.games.new(params[:game])
    if @game.save
      redirect_to root_path, :notice => "New Game Created"
    else
      flash[:alert] = "Oops, something went wrong"
      render :new
    end
  end

  def destroy
    @game = current_user.games.find(params[:id])
    #remove all invites to users for this game
    Invite.remove_all_invites_for_game(@game.id)
    if @game.destroy
      redirect_to root_path, :notice => "Game Deleted"
    else
      redirect_to root_path, :notice => "Oops, something went wrong"
    end
  end
  
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def create
    invited_user = User.find_by_username(params[:player_username])
    @invite = invited_user.invites.new(from_user_id: current_user.id, game_id: params[:game_id])
    if @invite.save
      redirect_to root_path
    else
      redirect_to game_player_path(params[:game_id])
    end
  end

  def update
    invite = current_user.invites.find(params[:id])
    game = Game.find(invite.game_id)
    player = game.players.new(name: current_user.username, email: current_user.email, user_id: current_user.id)
    if player.save
      invite.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @game = Game.find_by_game_key(params[:game_key])
    redirect_to root_path unless @game
    @player = @game.players.new(name: current_user.username, email: current_user.email)
  end

end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  
  def index
    redirect_to games_path if current_user
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_user!

#Creating an index of players on the server (should be able to search via location? - amend to user profile?)
  def index
    #only want to display usernames for linking into a game
    @player_names = User.all.map {|user| user.username}
    @game_id = current_user.games.find(params[:game_id])
  end

  def new
    @player = current_user.games.find(params[:game_id]).players.new
    @game_id = params[:game_id]
  end

  def create
    game = Game.find(params[:game_id])
    player = game.players.new(params[:player])
    if User.find_by_email(player.email) && player.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def caught
    player = Player.find_by_email(current_user.email)
    player.update_attributes(role: "zombie") if player
    respond_to do |format|
      format.js
      format.html {redirect_to game_path(params[:game_id])}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def display_login
    if user_signed_in?
      link_to( "Log Out", destroy_user_session_path, :method => :delete) 
    else
      link_to( "Log In", new_user_session_path) 
    end
  end

end

app/helpers/game_helper.rb
module GameHelper
  def owner?(game)
    game.user == current_user
  end

  def is_user?(player)
    player.email == current_user.email 
  end

  def game_data(invite)
    Game.find(invite.game_id)

    #rescue if no id found.
    rescue ActiveRecord::RecordNotFound => e
    invite.destroy
    nil
  end

  def get_user_name(user_id)
    User.find(user_id).username
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/games/index.html.erb
<section>
  <h1> Zombie Game </h1>
  <article>
    <!-- start slipsum code -->

    <p>The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee. </p>

    <!-- please do not remove this line -->

    <div style="display:none;">
    <a href="http://slipsum.com">lorem ipsum</a></div>

    <!-- end slipsum code -->
  </article>
  <article>
  <% if @games.empty? %>
    <p> You don't seem to have any games setup. <%= link_to "Create a new game", new_game_path %> </p>
  <% else %>
    <h3>Your Game details</h3>
    <table class="table table-striped">
      <tr>
        <th>Title</th>
        <th>Start</th>
        <th>Finish</th>
        <th>Entires In By</th>
        <th>Players</th>
        <th>Owner</th>
        <th>Action</th>
      </tr>
      <% @games.each do |game| %>
      <tr>
        <% if owner?(game)%>
        <td><%= link_to game.title, game_path(game.id) %></td>
        <%else%>
        <td><%= link_to game.title, game_path(game.id, game_key: game.game_key) %></td>
        <%end%>
        <td><%= game.start.strftime("%a #{game.start.day.ordinalize} %b") %></td>
        <td><%= game.finish.strftime("%a #{game.finish.day.ordinalize} %b") %></td>
        <td><%= game.entries_close.strftime("%a #{game.entries_close.day.ordinalize} %b") %></td>
        <td><%= game.players.count %></td>
        <td><% if owner?(game)%> you <% else %> <%= game.user.username %> <% end %>
        <td><%= link_to "x", game_path(game.id), :method => "delete" if owner?(game) %></td>
      </tr>
      <% end %>
    </table>
    <%= link_to "Create a new game", new_game_path, :class => "btn" %>
    <% end %>
  </article>
  <article>
    <% unless @invites.empty? %>
    <div class="row">
      <div class="span8">
        <h3>Your invites to other games</h3>
        <table class="table table-striped">
          <tr>
            <th>Title</th>
            <th>Start</th>
            <th>Finish</th>
            <th>Entires In By</th>
            <th>From</th>
            <th>Action</th>
          </tr>
          <% @invites.each do |invite| %>
          <%gamedata = game_data(invite)%>
          <%if gamedata%>
              <tr>
                <td><%= gamedata.title %></td>
                <td><%= gamedata.start.strftime("%a #{gamedata.start.day.ordinalize} %b") %></td>
                <td><%= gamedata.finish.strftime("%a #{gamedata.finish.day.ordinalize} %b") %></td>
                <td><%= gamedata.entries_close.strftime("%a #{gamedata.entries_close.day.ordinalize} %b") %></td>
                <td><%= get_user_name(invite.from_user_id) %></td>
                <td><%= link_to "accept", invite_path(invite.id), :class => "btn", :method => "put" %><%= link_to "decline", invites_path(invite.id), :class => "btn", :method => "delete" %></td>
              </tr>
            <% end %>
          </div>
        </div>
        <% end %>
      </table>
    <% end %>
  </article>
</section>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <%= f.label :title %><%= f.text_field :title %> <br/>
  <%= f.label :start %><%= f.date_select :start %><br/>
  <%= f.label :entries_close %><%= f.date_select :entries_close %><br/>
  <%= f.label :finish %><%= f.date_select :finish %><br/>
  <%= f.submit "Create Game" %>
<% end %>

<%= link_to "Back", root_path %>
      

app/views/games/show.html.erb
<%= content_tag "div", "", id: 'player_collection', data: { players: @game.players} %>

<h1><%= @game.title %></h1>
<h3>Owner: <%= @game.user.username %></h3>
<section>
  <article>
    <ul>
      <li>Start: <%=@game.start.strftime("%a #{@game.start.day.ordinalize} %b")%></li>
      <li>Finish: <%=@game.finish.strftime("%a #{@game.finish.day.ordinalize} %b") %></li>
      <li>Entries in by: <%=@game.entries_close.strftime("%a #{@game.entries_close.day.ordinalize} %b") %></li>
      <li>Players: <%=@game.players.count %></li>
    </ul>
  </article>
  <article>
    <h2>Players</h2>
    <% if @game.players.empty? %>
      <p>You dont have any players yet, go get some! <%= link_to "Add/invite player", new_game_player_path(@game.id)%></p>
    <% else %>
      <ul class='thumbnails', id="players">
        <li>Loading....</li>
      </ul>
    <% end %>
    <%= link_to "Add/invite player", game_players_path(@game.id)%></p>
  </article>
  <%= link_to "back", root_path %>
</section>

app/views/joins/new.html.erb
<h1>Join : <%= @game.title %>?</h1>
<h3>Owner: <%= @game.user.username %></h3>
<section>
  <article>
    <ul>
      <li>Start: <%=@game.start.strftime("%a #{@game.start.day.ordinalize} %b")%></li>
      <li>Finish: <%=@game.finish.strftime("%a #{@game.finish.day.ordinalize} %b") %></li>
      <li>Entries in by: <%=@game.entries_close.strftime("%a #{@game.entries_close.day.ordinalize} %b") %></li>
      <li>Players: <%=@game.players.count %></li>
    </ul>
  </article>

<section>
  <%= form_for @player, :url => game_players_path(@game) do |f| %>
    Your Name: <%= @player.name %><br/>
    Your Email: <%= @player.email %><br/><br/>
    <%= f.submit "Join" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Zgame" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href= "/">Zgame</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <li><%= display_login %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>

      <footer>
        <p>&copy; Fishplate 2012</p>
      </footer>
    
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/mains/index.html.erb
<div class="row">
  <div class="span9">
    <h1> Welcome to Zombie Game</h1>
  </div>
</div>

<div class="row">
  <div class="span6">
    <!-- start slipsum code -->

    <p>Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. </p>

    <p>Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. </p>

    <p>You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man. </p>

    <iframe width="420" height="315" src="http://www.youtube.com/embed/gxFiVgD2xNk" frameborder="0" allowfullscreen></iframe>

    <!-- please do not remove this line -->

    <div style="display:none;">
    <a href="http://slipsum.com">lorem ipsum</a></div>

    <!-- end slipsum code -->

  </div>
  <div class="span3">
    <%= image_tag "zombie4.png", :class => "img-rounded"%>
  </div>
</div>

app/views/players/index.html.erb
<h1>Players available</h1>

<section>
  <%@player_names.each do |player| %>
    <!-- Don't want to see my name in there :D -->
    <%unless player == current_user.username%>
      <li><%=player%> <%=link_to "invite", invites_path(:player_username => player, :game_id => @game_id), :class => "btn", :method => :post %></li>
    <% end %>
  <% end %>
</section>

app/views/players/new.html.erb
<h1>invite a new player</h1>
<section>
send a invite to player.
</section>

<%= link_to "back", game_path(@game_id)%>